In [8]:

#Q1
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

# Interchange its rows and columns (transpose the array)
transposed_array = np.transpose(array)

# Output the original and transposed arrays
print("Original Array:")
print(array)

print("\nTransposed Array:")
print(transposed_array)

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

# Interchange its rows and columns (transpose the array)
transposed_array = np.transpose(array)

# Output the original and transposed arrays
print("Original Array:")
print(array)

print("\nTransposed Array:")
print(transposed_array)

Original Array:
[[19 94 58]
 [69 71 93]
 [21 10 18]]

Transposed Array:
[[19 69 21]
 [94 71 10]
 [58 93 18]]
Original Array:
[[ 1  8 97]
 [66 68 56]
 [41 49 67]]

Transposed Array:
[[ 1 66 41]
 [ 8 68 49]
 [97 56 67]]


In [9]:
#Q2
import numpy as np

# Generate a 1D array with 10 elements (IDs)
array = np.arange(1, 11)

# Reshape into a 2x5 array
reshaped_2x5 = array.reshape(2, 5)

# Reshape into a 5x2 array
reshaped_5x2 = array.reshape(5, 2)

# Output the arrays
print("Original 1D Array:")
print(array)

print("\nReshaped 2x5 Array:")
print(reshaped_2x5)

print("\nReshaped 5x2 Array:")
print(reshaped_5x2)



Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped 2x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped 5x2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [10]:
#Q3Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around it to make a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Output the arrays
print("Original 4x4 Array:")
print(array_4x4)

print("\nArray with Zero Border (6x6):")
print(array_6x6)

Original 4x4 Array:
[[0.17610523 0.92645034 0.54619851 0.17553132]
 [0.94462103 0.37515826 0.16909658 0.30578217]
 [0.57158261 0.43240382 0.27318305 0.27536019]
 [0.3568372  0.54414051 0.65838116 0.80224408]]

Array with Zero Border (6x6):
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.17610523 0.92645034 0.54619851 0.17553132 0.        ]
 [0.         0.94462103 0.37515826 0.16909658 0.30578217 0.        ]
 [0.         0.57158261 0.43240382 0.27318305 0.27536019 0.        ]
 [0.         0.3568372  0.54414051 0.65838116 0.80224408 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [11]:
#Q4 Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

# Output the array
print("Array of integers from 10 to 60 with a step of 5:")
print(array)

Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


In [12]:
#Q5Create a NumPy array of strings ['python', 'numpy', 'pandas'].
#Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)

# Output the transformed arrays
print("Original Array:")
print(array)

print("\nUppercase Array:")
print(uppercase_array)

print("\nLowercase Array:")
print(lowercase_array)

print("\nTitle Case Array:")
print(titlecase_array)

Original Array:
['python' 'numpy' 'pandas']

Uppercase Array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Array:
['python' 'numpy' 'pandas']

Title Case Array:
['Python' 'Numpy' 'Pandas']


In [13]:
#Q6Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np

# Create a NumPy array of words
array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_array = np.char.join(' ', array)

# Output the original and spaced arrays
print("Original Array:")
print(array)

print("\nArray with Spaces Between Characters:")
print(spaced_array)

Original Array:
['python' 'numpy' 'pandas']

Array with Spaces Between Characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


In [14]:
#Q7Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise operations
addition = np.add(array1, array2)
subtraction = np.subtract(array1, array2)
multiplication = np.multiply(array1, array2)
division = np.divide(array1, array2)

# Output the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [15]:
#Q8Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Output the identity matrix and diagonal elements
print("5x5 Identity Matrix:")
print(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)



5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [16]:
#Q9 Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Function to check if a number is prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = np.array([num for num in random_integers if is_prime(num)])

# Output the array of random integers and the prime numbers found
print("Random Integers:")
print(random_integers)

print("\nPrime Numbers in the Array:")
print(prime_numbers)

Random Integers:
[923 567 518 809 737 639 475 213  18 213 699 663 122 376 759 677 254 666
   6 123 224 593  78 387 721 586 255  63 711 199 961 292 717 153 695 751
 242 586 290 453 659 519 231 570 496 128 289 704 802 232 342 531 363  14
 922 555 950 408 249 571 809 727 377 415 580 686 550 514 200 771 506 952
  67  96 853 997 872 122 815 755 880 726 368 286 657 314 817 400 357 261
 201 937 390 421  72 245 475 205 878 131]

Prime Numbers in the Array:
[809 677 593 199 751 659 571 809 727  67 853 997 937 421 131]


In [17]:
#Q10Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# For simplicity, let's use random temperatures between 15 and 35 degrees Celsius
np.random.seed(0)  # For reproducibility
daily_temperatures = np.random.randint(15, 36, size=30)

# Calculate weekly averages
# There are 4 full weeks in 30 days (28 days) and 2 extra days
weekly_averages = [daily_temperatures[i:i+7].mean() for i in range(0, 28, 7)]

# Add the average for the last incomplete week (last 2 days)
last_week_avg = daily_temperatures[28:].mean()
weekly_averages.append(last_week_avg)

# Display the results
print("Daily Temperatures for the Month (30 Days):")
print(daily_temperatures)
print("\nWeekly Averages:")
for week_num, avg in enumerate(weekly_averages, start=1):
    print(f"Week {week_num}: {avg:.2f}°C")

Daily Temperatures for the Month (30 Days):
[27 30 15 18 18 22 24 34 33 19 21 27 16 21 22 29 32 20 28 23 24 35 34 31
 34 20 30 30 15 33]

Weekly Averages:
Week 1: 22.00°C
Week 2: 24.43°C
Week 3: 25.43°C
Week 4: 30.57°C
Week 5: 24.00°C
